services:
  eureka-server:
    build: ./eureka-server
    ports:
      - "8761:8761"

  api-gateway:
    build: ./api-gateway
    env_file:
      - .env
    ports:
      - "8080:8080"
    depends_on:
      - eureka-server

  resource-service-db:
    env_file:
      - .env
    image: postgres:alpine
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${RESOURCES_DB}
    volumes:
      - ./init-scripts/resource-db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5433:5432"

  song-service-db:
    env_file:
      - .env
    image: postgres:alpine
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${SONGS_DB}
    volumes:
      - ./init-scripts/song-db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5434:5432"

  resource-service:
    build: ./resource-service
    env_file:
      - .env
    depends_on:
      - resource-service-db
      - eureka-server

  song-service:
    build: ./song-service
    env_file:
      - .env
    deploy:
      replicas: 2
    depends_on:
      - song-service-db
      - resource-service
      - eureka-server
