global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'api-gateway'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['api-gateway:8080']

  - job_name: 'resource-processor'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['resource-processor:8083']

  - job_name: 'resource-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['resource-service:8082']

  - job_name: 'storage-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['storage-service:8088']

  - job_name: 'song-service'
    metrics_path: '/actuator/prometheus'
    dns_sd_configs:
      - names: ['song-service']
        type: 'A'
        port: 8081
