spring:
  application:
    name: auth-server

auth:
  clients:
    gateway-secret: ${GATEWAY_CLIENT_SECRET:gateway-secret}
  jwk-key-size: 2048

logging:
  level:
    org.springframework.security: INFO
    org.springframework.security.oauth2: DEBUG

server:
  port: ${AUTH_SERVER_PORT:9000}
