spring:
  application:
    name: auth-server

  security:
    oauth2:
      authorization:
        issuer-uri: ${AUTH_SERVER_URL:http://localhost:9000}

      resourceserver:
        jwt:
          jwk-set-uri: ${AUTH_SERVER_URL:http://localhost:9000}/oauth2/jwks

server:
  port: ${AUTH_SERVER_PORT:9000}

auth:
  clients:
    storage-secret: ${STORAGE_CLIENT_SECRET:storage-secret}
    user-secret: ${USER_CLIENT_SECRET:user-secret}
    gateway-secret: ${GATEWAY_CLIENT_SECRET:gateway-secret}
  jwk-key-size: 2048
